# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
    build:
        if: "!contains(github.event.head_commit.message, 'skip-ci')"

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@octocat' # Defaults to the user or organization that owns the workflow file:
            - run: yarn --frozen-lockfile
            - name: Build
              run: |
                  yarn build
            - name: Build-browser
              if: github.ref == 'refs/heads/master'
              run: |
                  yarn build-browser
            - run: yarn test
            - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Bump & Publish
              if: github.ref == 'refs/heads/master'
              run: |
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
                  git config user.name "$GITHUB_ACTOR"
                  yarn bump
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
